baseurl = "https://paul.kinlan.me/"
languageCode = "en-us"
title = "Podcast in a box"
description = ""
Copyright = "Paul Kinlan 2019"
paginate = 20
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js", "mjs"]

[permalinks]
  post = "/:title/"

[author]
    name = "Paul Kinlan"
    email = "paul.kinlan@gmail.com"
    
[params]
  author = "Paul Kinlan"
  analyticsid = "UA-114468-20"

[taxonimies]
  tag = "tags"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  section = ["HTML","RSS"]
  page = ["HTML"]

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 10

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
  name  = "tags"
  weight = 100
