baseURL = "https://podcastinabox.kinlan.now.sh"
languageCode = "en-us"
title = "Podcast in a box"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:title/"

[params]
  author = "Author Name"
  image = "/images/web_hi_res_512.png"
  email = "email@email.com"
  description = "Awesome Podcast"
  category = ""
  subcategory = ""
  explicit = "no"
  block = "no"
  
[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js", "mjs"]
  [mediaTypes."application/json"]
    suffixes = ["json", "manifest"]

[outputFormats]
  [outputFormats.WebAppManifest]
    baseName = "manifest"
    isPlainText = true
    mediaType = "application/json"

[outputs]
  home = ["HTML", "RSS", "WebAppManifest"]
  section = ["HTML"]
  page = ["HTML"]