baseURL = "https://podcastinabox.kinlan.now.sh"
languageCode = "en-us"
title = "Podcast in a box"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:title/"

[params]
  author = "Author Name"
  image = "/images/web_hi_res_512.png"
  email = "email@email.com"
  description = "Awesome Podcast"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]